name: Flutter Android Build & SHA-1 Key

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          # Naye Flutter version ka upyog karein jo Dart 3.6.0 ya usse upar ke saath aata hai
          flutter-version: '3.19.6' 

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Get APK SHA-1 Key
        run: |
          keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android

      - name: Upload APK as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
