name: Android Build and SHA1 Key

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Generate SHA1 Key
      run: |
        keytool -list -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android
      shell: bash
