name: Generate SHA-1 Key

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate SHA-1 Key
        id: sha1_key
        run: |
          KEY_STORE_FILE_PATH="keystore.jks"
          echo "${{ secrets.ANDROID_SIGNING_KEY_STORE_FILE }}" | base64 --decode > "$KEY_STORE_FILE_PATH"

          SHA1_KEY=$(keytool -list -v -keystore "$KEY_STORE_FILE_PATH" -alias "${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}" -storepass "${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}" -keypass "${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" | grep 'SHA1:' | cut -d ' ' -f 10)
          echo "SHA-1 Key is: $SHA1_KEY"
          echo "sha1_key=$SHA1_KEY" >> $GITHUB_ENV
