name: Flutter & Android SDK Version Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Ya phir tumhare pubspec.yaml ke hisaab se

      - name: Flutter version
        run: flutter --version

      - name: Dart version
        run: dart --version

      - name: Android SDK version
        run: |
          sdkmanager --list | head -n 20 || echo "Android SDK not fully available in this runner"
