name: Android Build and SHA1 Key

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Generate Debug Keystore if not exists
      run: |
        if [ ! -f android/app/debug.keystore ]; then
          echo "Generating debug keystore..."
          keytool -genkey -v -keystore android/app/debug.keystore -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -alias androiddebugkey -dname "CN=Android Debug, OU=Android, O=Android, L=Local, ST=State, C=Country"
        else
          echo "Debug keystore already exists."
        fi

    - name: Generate SHA1 Key
      run: |
        keytool -list -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android
      shell: bash
