name: Generate SHA-1 Key

on:
  push:
    branches:
      - main

jobs:
  generate-sha1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SHA-1 key from a file (e.g. README.md)
        id: sha1
        run: |
          sha1=$(sha1sum README.md | awk '{ print $1 }')
          echo "SHA-1 Key: $sha1"
          echo "sha1=$sha1" >> $GITHUB_ENV

      - name: Copy SHA-1 Key
